version: "3.7"

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true  
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    user: 'elasticsearch'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    networks:
      - monitor
      
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.3.2
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - monitor
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.3.2
    user: root
    networks:
      - monitor
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: filebeat -e -strict.perms=false
    restart: on-failure
    depends_on:
      - elasticsearch

  census:
    container_name: census
    image: api-zipcode:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - PORT_EXTERNAL=8080
    labels:      
      - "elastic_index=springboot"
      - "send.logs=true"
      
    depends_on:
      - filebeat

volumes:
  elasticsearch-data:

networks:
  monitor:
    driver: bridge